exampleSite/config.toml
If you do not put `'/'` at the beginning, url will become `'/about/tags'` when transitioning from `'/about'` to `'/tags'`
@mismith0227 
とても良いテーマを作っていただきありがとうございます。
exampleSite/config.tomlをコピーして使っていたのですが、メニューのリンク遷移に問題があったので修正してみました。
=> Fix url of 'theme' and 'tags' in exampleSite/config.toml

layouts/index.html
I often want to share posts with colleagues to ask for feedback before I officially publish.
This PR hides posts from the index page if they have `hidden: true` in their front matter. This means you can only read the post if you happen to know the URL, much like GitHub's secret gist feature.
=> Hide content from index page using front matter param

layouts/_default/terms.html
Using `sanitizeurl` to ensure no extra slash in result url.  
Otherwise, it will produce something like `http://example.com//foo/bar`, which can cause error on some HTTP server.
=> Process BaseURL using `sanitizeurl`

layouts/_default/single.html
#40 sanitized the baseurl in terms.html to ensure no double-slashes. This employs the same sanitization in single.html.
=> Sanitize baseurl consistently

layouts/partials/footer.html
Google Analytics tracking code is not included when running Hugo server.
=> Fixes #44 

exampleSite/config.toml, exampleSite/static/css/custom.css, layouts/partials/head.html
This PPR add functionality to define `custom_css` files in config and add them to `static/css`.
This will allow easy adjustments and customization of the styles.
=> Adding support for custom css styles

layouts/_default/single.html
As of Hugo 0.50, .Prev/.Next are .NextPage/.PrevPage respectively. Reference https://github.com/gohugoio/hugo/pull/5252
=> .Prev and .Next deprecated, update pagination to .NextPage and .PrevPage

layouts/partials/head.html
With Hugo version 0.55.1, this template gives the following warnings:
```
WARN 2019/04/14 20:47:15 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/04/14 20:47:15 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
WARN 2019/04/14 20:47:15 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like:
{{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
Total in 109 ms
```
This PR updates the `head.html` template to use the updated Hugo syntax.
=> fix(head): update Hugo functions which will be deprecated

layouts/partials/head.html, layouts/partials/mathjax_support.html
Added MathJax support to enable rendering of LaTeX math type for posts with the parameter `mathjax = true`.
=> Added MathJax support

layouts/_default/list.html, layouts/index.html
In Hugo v0.57.0, a breaking change was introduced to the `.Pages`
variable [1]. This adopts the new .Site.RegularPages syntax.
https://github.com/gohugoio/hugo/issues/6153
=> build: update for Hugo v0.57+

layouts/_default/single.html
When there are multiple sections, NextPage and PrevPage will interleave
pages in them.  To match existing pagination and perhaps user intuition,
instead use NextInSection and PrevInSection which will restrict to e.g.
posts.
=> (Next|Prev)Page -> (Next|Prev)InSection

exampleSite/config.toml, layouts/partials/footer.html, layouts/partials/head.html
It has been raised already in #129 that there's a default setting for Google Analytics that makes it portable across different themes.
https://gohugo.io/templates/internal/#google-analytics
=> Use standard Hugo template for Google Analytics

layouts/_default/list.html
Description:
Fix a problem on listing posts with specific tag, and category.
In a default layout, list.xml, there is no routines to draw items depends on tags or categories. 
I do pull request to fix the problem with using .Data.Pages variable.
=> Fix a bug on listing posts in tag, categories

layouts/partials/head.html
Using `HUGO_ENV` or `Site.Params.env` to enable google analytics script is bad because it is not intuitive to the user. This PR replaces the env check with .`Site.IsServer`, which is usually true for development.
Reference: https://gohugo.io/variables/site/#site-variables-list
=> Better env check for google analytics script

layouts/partials/header.html, layouts/partials/header_custom.html
DESCRIPTION: Adds a header_custom.html that parallels footer_custom.html and head_custom.html,
allowing custom styling (e.g. injecting the menu or other navigational content) between
the site header and page content.
=> Add header_custom for injecting custom header content

layouts/_default/li.html, layouts/_default/single.html, layouts/partials/timestamp.html
This is particularly useful for users (i.e. me) who would like to change the default date formatting and perhaps remove the 'posted on' text.
=> Refactor 'posted on' code to a timestamp partial

README.md, exampleSite/content/posts/hiding-the-date.md, layouts/_default/single.html
This closes issue #71.
By the way @mismith0227 - when I follow the instructions to run the site, I cannot serve the `exampleSite` folder, it complains about the zoom shortcode not being present - do you know why this is? I was hoping to be able to test this on the example site first!
=> feat: add 'hideDate' parameter to hide the date

README.md, package.json
Currently if you clone the code and follow the instructions, running `hugo serve` will result in the following error:
```
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
Run `hugo help new` for details.
```
This PR updates the `yarn run hugo` command to correctly serve the `exampleSite` folder with the local version of the theme. Live reload etc is also supported. This PR also updates the documents.
Fixes #147
=> fix: serving the example site locally with `yarn run hugo` now works

exampleSite/config.toml, layouts/_default/li.html, layouts/partials/modified_date.html
add a new param: hideModifiedDate. If set to false, the last modified time of post is displayed.A site global configuration is also added, enableGitInfo. If set to true, the last modified time will get from git commits. More can see this: https://gohugo.io/getting-started/configuration/#enablegitinfo
preview
=> feat: add last modified time to posts

exampleSite/config.toml
Paginate was not working for me on Hugo v0.82 until I moved it out of `[params]`
=> Move paginate out of params

i18n/en.toml, i18n/pt.toml, layouts/partials/header.html, layouts/partials/link.html, layouts/partials/modified_date.html, layouts/partials/pagination.html, layouts/partials/reading_time.html, layouts/partials/related.html, layouts/partials/siteinfo.html, layouts/partials/timestamp.html, layouts/partials/word_count.html
Hey! :)
For my blog, I needed to adapt the code a bit to be able to add portuguese translations into it.
* Removes static strings from the template and replace it with `i18n` function calls;
* Adds `i18n` folder containing original english strings + brazilian portuguese translations
Thanks for sharing the template on GitHub!
=> Adds i18n support

layouts/_default/single.html, layouts/_default/terms.html
Currently, the link-href url for tags in both, a post page and the tag overview, looks like this for example.com:
https://example.com/tags/https//example.com//tags/nginx
This is obviously not correct and comes from calling urlize on the BaseURL which makes it URL safe per documentation. Instead, use absURL which is meant for this purpose.
=> fix invalid tag url
